#!/usr/bin/env python3
"""Compute objective grounding stats for a Lab Journal entry.

The journal entry itself (reports/journal/<date>.json) is human prose written
by Claude during a working session — it can't be generated by the unattended
daily scan (scripts/git_health.py), since nothing but a live conversation can
write it. That's exactly why this script exists: the prose needs a checkable,
objective factual basis, or "an interesting dataset over time" quietly
degrades into unverifiable vibes. Run this BEFORE writing an entry; write the
entry FROM its output, not from memory of the conversation alone.

Scope: commits across ALL local branches (--all), not just each repo's
default branch — real work happens on feature/sandbox branches in this
ecosystem (see ecosystem-cleanliness-and-maintenance-plan.md §3's finding),
and "what we did" should reflect that.

Usage:
    python scripts/journal_stats.py                  # since the last journal entry
    python scripts/journal_stats.py --since 2026-07-20
"""
from __future__ import annotations

import argparse
import json
import subprocess
from datetime import datetime, timezone, date, timedelta
from pathlib import Path

LAB_ROOT = Path(__file__).resolve().parents[2]
JOURNAL_DIR = Path(__file__).resolve().parents[1] / "reports" / "journal"


def run(cmd: list[str], cwd: Path) -> str:
    result = subprocess.run(cmd, cwd=cwd, capture_output=True, text=True)
    return result.stdout.strip()


def last_journal_date() -> date | None:
    if not JOURNAL_DIR.exists():
        return None
    dates = sorted(p.stem for p in JOURNAL_DIR.glob("*.json") if p.stem != "index")
    if not dates:
        return None
    return datetime.strptime(dates[-1], "%Y-%m-%d").date()


def commits_since(repo: Path, since: date) -> list[dict]:
    since_str = since.isoformat()
    log = run(
        ["git", "log", "--all", f"--since={since_str} 00:00:00", "--date=iso-strict",
         "--pretty=format:%H|%ad|%an|%s"],
        repo,
    )
    if not log:
        return []
    commits = []
    for line in log.splitlines():
        parts = line.split("|", 3)
        if len(parts) == 4:
            sha, date_str, author, subject = parts
            commits.append({"sha": sha[:8], "date": date_str, "author": author, "subject": subject})
    return commits


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--since", type=str, default=None, help="YYYY-MM-DD; default: day after the last journal entry")
    parser.add_argument("--root", type=Path, default=LAB_ROOT)
    args = parser.parse_args()

    if args.since:
        since = datetime.strptime(args.since, "%Y-%m-%d").date()
    else:
        last = last_journal_date()
        since = (last + timedelta(days=1)) if last else date.today()

    today = date.today()
    repos: dict[str, list[dict]] = {}
    for entry in sorted(args.root.iterdir()):
        if not entry.is_dir() or entry.name.startswith("."):
            continue
        if not (entry / ".git").exists():
            continue
        commits = commits_since(entry, since)
        if commits:
            repos[entry.name] = commits

    total_commits = sum(len(c) for c in repos.values())
    result = {
        "period_start": since.isoformat(),
        "period_end": today.isoformat(),
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "had_activity": total_commits > 0,
        "total_commits": total_commits,
        "repos_touched": list(repos.keys()),
        "commits_by_repo": repos,
    }
    print(json.dumps(result, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
